name: GitHub Actions
on: [push]
jobs:
    init:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: Check out repository code
              uses: actions/checkou@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm install
            - name: build project
              run: npm run build
            - name: format(prettier) project
              run: npm run format
            - name: test project
              run: npm run test
